
# cd C:\Projects\minsur\curso_python
# conda env create -f environment.yml

name: pyrmenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.3
  - pandas=2.0.1
  - numpy=1.26.4
  - scikit-learn
  - scipy=1.14.1
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - openpyxl=3.1.2
  - pytest=7.3.1
  - ipykernel
  - ipywidgets
  - setuptools
  - gstools=1.7.0
  - trimesh=4.6.12
  - open3d
  - pip
  - pip:
      - build
      - manifold3d
      - pywin32; sys_platform == "win32"
